<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spthy</string>
	</array>
	<key>name</key>
	<string>Tamarin</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>//comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(&quot;|#|$|(|)|,|.|:|[|]|{|}|~|&lt;|&gt;|==&gt;|&lt;=&gt;|F|T|All|Ex|\\||&amp;)\b</string>
			<key>name</key>
			<string>keyword.other.operators.spthy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(aenc|sdec|senc|sdec|sign|verify|hashing|signing|h|sk|pk|fr|Fr|pb|lts|diffie-hellman|symmetric-encryption|asymmetric-encryption)\b</string>
			<key>name</key>
			<string>keyword.other.constr.spthy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(axiom|lemma|equations|functions|builtins|protocol|property|in|let|theory|begin|end|subsection|section|text|exists-trace|all-traces|enable|rule|assertions|modulo|default_rules|anb-proto|:|-&gt;|&lt;-|--&gt;|--\\[|\\]-&gt;)\b</string>
			<key>name</key>
			<string>keyword.other.decl.spthy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>{\||\|}|{|}|\.\.|:|#|&lt;-|&lt;-&gt;|==|\!=|&lt;|&gt;|&lt;=|&gt;=|@|&amp;</string>
			<key>name</key>
			<string>keyword.operator.spthy</string>
		</dict>
	<key>scopeName</key>
	<string>source.spthy</string>
	<key>semanticClass</key>
	<string>source.spthy</string>
	<key>uuid</key>
	<string>A6B019CB-75BF-4D9A-AAB1-703F6B6D143B</string>
</dict>
</plist>
